.equ DEBOUNCEH, 14
.equ DEBOUNCEL, 166

.equ HPW, 2
.equ LPW, 238

.equ POS_0, 0
.equ POS_1, 1
.equ POS_2, 2
.equ POS_3, 3
.equ POS_4, 4
.equ POS_5, 5
.equ POS_6, 6

.equ PWM_POS_0, 20
.equ PWM_POS_1, 25
.equ PWM_POS_2, 30
.equ PWM_POS_3, 35
.equ PWM_POS_4, 40
.equ PWM_POS_5, 45
.equ PWM_POS_6, 50
.equ PWM_POS_7, 55
.equ PWM_POS_8, 60
.equ PWM_POS_9, 65
.equ PWM_POS_a, 70
.equ PWM_POS_b, 75
.equ PWM_POS_c, 80
.equ PWM_POS_d, 85
.equ PWM_POS_e, 90

.equ POS_L_LEFT, 0
.equ POS_LEFT, 1
.equ POS_MID, 2
.equ POS_RIGHT, 3
.equ POS_R_RIGHT, 4

.equ LLEFTC, 20
.equ LEFTC, 35
.equ MIDC, 50
.equ RIGHTC, 65
.equ RRIGHTC, 80

.equ ears_START, 0
.equ ears_PRESS1, 1
.equ ears_HOLD1, 2
.equ ears_RELEASE1, 3
.equ ears_PRESS2, 4
.equ ears_HOLD2, 5
.equ ears_RELEASE2, 6
.equ ears_PRESS3, 7
.equ ears_HOLD3, 8
.equ ears_RELEASE3, 9
.equ ears_AUX_STATE0, 10
.equ ears_AUX_STATE1, 11
.equ ears_AUX_STATE2, 12
.equ ears_AUX_STATE3, 13

.equ TIME_ears_H, 50
.equ TIME_ears_L, 255

.equ EAR_STATE_IDLE, 0
.equ EAR_STATE_SURPRISE, 1
.equ EAR_STATE_ANGRY, 2
.equ EAR_STATE_DISTRACTED0, 3
.equ EAR_STATE_DISTRACTED1, 4
.equ EAR_STATE_DISTRACTED2, 5
.equ EAR_STATE_DISTRACTED3, 6

.equ AUX_COUNTER_H, 25
;.equ AUX_COUNTER_H, 12
.equ AUX_COUNTER_L, 255

